version: ~> 1.0
os: linux
dist: focal
language: minimal
services:
  - docker

# Because metatool checks for certain commits
git:
  depth: false

script:
  - echo "\n" | ./metatool test

notifications:
  irc:
    channels:
      - "chat.freenode.net#albertlauncher"
    on_success: change
    on_failure: change
    template:
      - "%{repository_name}#%{build_number} (%{commit}) : %{message}\n\n%{build_url}"
